branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment:
  GH_TOKEN:
    secure: CLmIAAjz8+SAxpE4XPGV0W6muQvaZLijIxm0Tvph8ZcKMQwNa1gNrkBlloqRZ1/S

  matrix:
    - nodejs_version: '8'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

matrix:
  fast_finish: true
build: off
shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run build
  - ps: if($env:APPVEYOR_REPO_TAG -eq "true") { npm run release } else { echo "Not a tagg" }
